name: email_alarm
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.3+4

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_background_service_ios: ^5.0.0
  flutter_hooks: ^0.20.4
  flutter_local_notifications: ^16.3.0
  flutter_ringtone_player: ^4.0.0+2
  flutter_riverpod: ^2.4.9
  flutter_signin_button: ^2.0.0
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  permission_handler: ^11.2.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  pedantic_mono:
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  android: flutter build apk --release